name: Build and Archive SwiftUI App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Xcode
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: '16.2.0'

            - name: Resolve Swift Packages
              run: xcodebuild -resolvePackageDependencies -project H5Scann.xcodeproj -scheme H5Scann

            - name: Build and archive
              run: |
                  xcodebuild clean archive \
                    -project H5Scann.xcodeproj \
                    -scheme H5Scann \
                    -configuration Release \
                    -sdk iphoneos \
                    -archivePath ${{ github.workspace }}/build/H5Scann.xcarchive \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
                    PROVISIONING_PROFILE_SPECIFIER="" DEVELOPMENT_TEAM=""

            - name: Create ExportOptions.plist
              run: |
                  cat > ExportOptions.plist <<EOF
                  <?xml version="1.0" encoding="UTF-8"?>
                  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
                  <plist version="1.0">
                  <dict>
                      <key>method</key>
                      <string>debugging</string>
                      <key>teamID</key>
                      <string></string>
                      <key>signingStyle</key>
                      <string>none</string>
                      <key>compileBitcode</key>
                      <false/>
                      <key>uploadBitcode</key>
                      <false/>
                      <key>uploadSymbols</key>
                      <false/>
                      <key>signingCertificate</key>
                      <string></string>
                      <key>provisioningProfiles</key>
                      <dict/>
                  </dict>
                  </plist>
                  EOF

            - name: Export IPA
              run: |
                  ls -l ExportOptions.plist
                  cat ExportOptions.plist
                  xcodebuild -exportArchive \
                    -archivePath ${{ github.workspace }}/build/H5Scann.xcarchive \
                    -exportOptionsPlist ExportOptions.plist \
                    -exportPath ${{ github.workspace }}/build
                    -allowProvisioningUpdates \
                    -exportFormat ipa \
                    CODE_SIGNING_REQUIRED=NO \
                    CODE_SIGN_IDENTITY=""

            - name: Upload IPA to GitHub Releases
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ github.workspace }}/build/H5Scann.ipa
                  asset_name: H5Scann.ipa
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
